export { default as AboutMe } from "./AboutMe/AboutMe";
export { default as Contacts } from "./Contacts/Contacts";
export { default as Error } from "./Error/Error";
export { default as Footer } from "./Footer/Footer";
export { default as Intro } from "./Intro/Intro";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Projects } from "./Projects/Projects";
export { default as Skills } from "./Skills/Skills";
export { default as ThankYou } from "./ThankYou/ThankYou";